defaults:
  - ../reader@reader: pillar_encoder
  - ../backbone@backbone: sparse_resnet18
  - ../neck@neck: aspp
  - ../head@head: centerhead

_target_: det3d.models.detectors.single_stage.SingleStageDetector

