defaults:
  - ../preprocess/augmentation@augmentation

loading_pipelines:
  - load_pointcloud
  - load_box3d

prepare_label:
  centermap:
    _target_: det3d.datasets.pipelines.assign.AssignLabel
    gaussian_overlap : 0.1
    max_objs: 500
    min_radius: 2